#! /bin/sh
# Bspwm config
polybar primary &
polybar secondary &
bspc config top_padding 29 #14
bspc config border_width 1
bspc config window_gap 0
bspc config split_ratio 0.50
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true
bspc monitor DVI-D-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0

bspc config pointer_modifier mod1 # mod4 doesn't work 
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Rules
bspc rule -a URxvt border=off

# Autostart
xrandr --output HDMI-0 --right-of DVI-D-0
feh --no-fehbg --bg-scale ~/wall.png
